## Global Variabel
@BaseUrl = https://pam-2026-p4-ifs23047-be.helgazefanya.site:8080/
#@BaseUrl = http://127.0.0.1:8000

## Profile
## ===========================================

### Mengambil semua data tumbuhan
# @name GetProfile
GET {{BaseUrl}}/profile
Content-Type: application/json

### Mengambil photo profil
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Content-Type: application/json


## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json

### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id-nya
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Melihat gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah hanya data plant berdasarkan id-nya
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary--

### Mengubah gambar dan data plant berdasarkan id-nya
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data plant berdasarkan id-nya
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json


## Pastries
## ===========================================

### Mengambil semua data pastry
# @name GetAllPastries
GET {{BaseUrl}}/pastries?search=
Content-Type: application/json

### Menambahkan data pastry baru
# @name PostPastries
POST {{BaseUrl}}/pastries
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="judul"

Croissant Cokelat
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Roti berlapis mentega yang renyah dengan isian cokelat Belgia yang lumer
--WebAppBoundary
Content-Disposition: form-data; name="bahanUtama"

Tepung terigu, Mentega, Cokelat, Ragi
--WebAppBoundary
Content-Disposition: form-data; name="infoAlergen"

Mengandung Gluten, Susu, dan kemungkinan jejak Kacang
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pastry.png"
Content-Type: image/png

< ./pastry.png
--WebAppBoundary--

> {%
    client.global.set("pastryId", response.body.data.pastryId);
    console.log(client.global.get("pastryId"))
%}

### Mengambil data pastry berdasarkan id-nya
# @name GetPastryById
GET {{BaseUrl}}/pastries/{{pastryId}}
Content-Type: application/json

### Melihat gambar pastry
# @name GetPastryImageById
GET {{BaseUrl}}/pastries/{{pastryId}}/image
Content-Type: application/json

### Mengubah hanya data pastry berdasarkan id-nya
# @name PutPastryOnlyData
PUT {{BaseUrl}}/pastries/{{pastryId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="judul"

Croissant Cokelat Premium
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Deskripsi terbaru: Menggunakan cokelat hitam 70%
--WebAppBoundary
Content-Disposition: form-data; name="bahanUtama"

Tepung terigu, Mentega, Cokelat Hitam
--WebAppBoundary
Content-Disposition: form-data; name="infoAlergen"

Mengandung Gluten dan Susu
--WebAppBoundary--

### Mengubah gambar dan data pastry berdasarkan id-nya
# @name PutPastry
PUT {{BaseUrl}}/pastries/{{pastryId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="judul"

Croissant Cokelat
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Roti berlapis mentega yang renyah dengan isian cokelat Belgia yang lumer
--WebAppBoundary
Content-Disposition: form-data; name="bahanUtama"

Tepung terigu, Mentega, Cokelat, Ragi
--WebAppBoundary
Content-Disposition: form-data; name="infoAlergen"

Mengandung Gluten, Susu, dan kemungkinan jejak Kacang
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pastry_v2.png"
Content-Type: image/png

< ./pastry_v2.png
--WebAppBoundary--

### Menghapus data pastry berdasarkan id-nya
# @name DeletePastry
DELETE {{BaseUrl}}/pastries/{{pastryId}}
Content-Type: application/json